# Generated by Django 5.2.12 on 2026-03-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
    ]
