# Generated by Django 5.2.12 on 2026-04-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_supplier_remove_medicine_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
