# Generated by Django 5.2.12 on 2026-04-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
